/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {AdPlacementResponseData} from './adPlacementResponseData';
import type {AdPlacementDetailResponseResultCode} from './adPlacementDetailResponseResultCode';

/**
 * 광고 지면 상세 Response
 */
export interface AdPlacementDetailResponse {
  data: AdPlacementResponseData;
  resultCode?: AdPlacementDetailResponseResultCode;
  resultMessage?: string;
}
