/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

export type AdPlacementByGoogleRequestAdOrderType =
  (typeof AdPlacementByGoogleRequestAdOrderType)[keyof typeof AdPlacementByGoogleRequestAdOrderType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdPlacementByGoogleRequestAdOrderType = {
  adpopcorn_video: 'adpopcorn_video',
  adpopcorn_interstitial: 'adpopcorn_interstitial',
  mezzo_video: 'mezzo_video',
  mezzo_interstitial: 'mezzo_interstitial',
  dawin_video: 'dawin_video',
  gpt_interstitial: 'gpt_interstitial',
  gpt_reward: 'gpt_reward',
} as const;
