/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {PageAdPlacementResponseData} from './pageAdPlacementResponseData';
import type {AdPlacementResponseResultCode} from './adPlacementResponseResultCode';

/**
 * 광고 지면 Response
 */
export interface AdPlacementResponse {
  data: PageAdPlacementResponseData;
  resultCode?: AdPlacementResponseResultCode;
  resultMessage?: string;
}
