/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {AdPlacementByAdPopcornRequestAdOrderType} from './adPlacementByAdPopcornRequestAdOrderType';
import type {AdPopcornAdConfig} from './adPopcornAdConfig';

/**
 * 애드팝콘 광고 지면 등록/수정 요청 Request
 */
export interface AdPlacementByAdPopcornRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  adOrderType: AdPlacementByAdPopcornRequestAdOrderType;
  /** 설정값 - android */
  android: AdPopcornAdConfig;
  /** 설정값 - ios */
  ios: AdPopcornAdConfig;
}
