/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {AdPlacementByMezzoRequestAdOrderType} from './adPlacementByMezzoRequestAdOrderType';
import type {MezzoAdConfig} from './mezzoAdConfig';

/**
 * 메조 광고 지면 등록/수정 요청 Request
 */
export interface AdPlacementByMezzoRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  adOrderType: AdPlacementByMezzoRequestAdOrderType;
  /** 설정값 - android */
  android: MezzoAdConfig;
  /** 설정값 - ios */
  ios: MezzoAdConfig;
}
