/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {AppAdminRegistrationRequestRole} from './appAdminRegistrationRequestRole';

/**
 * 앱 관리자 등록
 */
export interface AppAdminRegistrationRequest {
  /**
   * @minLength 4
   * @maxLength 50
   */
  username: string;
  /**
   * @minLength 4
   * @maxLength 2147483647
   */
  password: string;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  fullName: string;
  phone?: string;
  role: AppAdminRegistrationRequestRole;
}
