/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 답변 상태
 * @minLength 1
 */
export type CSStatusRequestStatus =
  (typeof CSStatusRequestStatus)[keyof typeof CSStatusRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CSStatusRequestStatus = {
  RECEIVED: 'RECEIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  ANSWERED: 'ANSWERED',
} as const;
