/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 처리 상태
 */
export type CSViewResponseDataStatus =
  (typeof CSViewResponseDataStatus)[keyof typeof CSViewResponseDataStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CSViewResponseDataStatus = {
  RECEIVED: 'RECEIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  ANSWERED: 'ANSWERED',
} as const;
