/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {PageEventEntryStatsResponseData} from './pageEventEntryStatsResponseData';
import type {EventEntryStatsResponseResultCode} from './eventEntryStatsResponseResultCode';

/**
 * 이벤트 응모 통계 Response
 */
export interface EventEntryStatsResponse {
  data: PageEventEntryStatsResponseData;
  resultCode?: EventEntryStatsResponseResultCode;
  resultMessage?: string;
}
