/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventAdPlacementInfoResponseDataAdOrderType} from './eventAdPlacementInfoResponseDataAdOrderType';
import type {EventAdPlacementInfoResponseDataAndroid} from './eventAdPlacementInfoResponseDataAndroid';
import type {EventAdPlacementInfoResponseDataIos} from './eventAdPlacementInfoResponseDataIos';

export interface EventAdPlacementInfoResponseData {
  id: string;
  adOrderType?: EventAdPlacementInfoResponseDataAdOrderType;
  android?: EventAdPlacementInfoResponseDataAndroid;
  ios?: EventAdPlacementInfoResponseDataIos;
  sort: number;
}
