/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 이벤트 조건 Response: 이벤트 유형 별 조건을 정의합니다.
 */
export interface EventConditionResponse {
  [key: string]: unknown;
}
