/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventAdminResponseDataEventType} from './eventAdminResponseDataEventType';
import type {EventAdPlacementInfoListResponse} from './eventAdPlacementInfoListResponse';
import type {EventAdminResponseDataEventCondition} from './eventAdminResponseDataEventCondition';

export interface EventAdminResponseData {
  id: string;
  appId: string;
  eventType: EventAdminResponseDataEventType;
  isView: boolean;
  introAdPlacementInfo?: EventAdPlacementInfoListResponse;
  resultAdPlacementInfo?: EventAdPlacementInfoListResponse;
  publicEventId: string;
  displayName?: string;
  iconUrl?: string;
  feedUrl?: string;
  summary?: string;
  condition?: string;
  rewardPrice?: number;
  description?: string;
  eventCondition?: EventAdminResponseDataEventCondition;
  landingPath?: string;
  sort: number;
  adminMenuName: string;
  createdAt: string;
  updatedAt?: string;
  view?: boolean;
}
