/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {PageEventEntryResponseData} from './pageEventEntryResponseData';
import type {EventEntryResponseResultCode} from './eventEntryResponseResultCode';

/**
 * 이벤트 응모 이력 Response
 */
export interface EventEntryResponse {
  data: PageEventEntryResponseData;
  resultCode?: EventEntryResponseResultCode;
  resultMessage?: string;
}
