/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventConditionResponse} from './eventConditionResponse';
import type {EventConditionResponseByDrawAllOf} from './eventConditionResponseByDrawAllOf';

export type EventConditionResponseByDraw = EventConditionResponse &
  EventConditionResponseByDrawAllOf &
  Required<
    Pick<
      EventConditionResponse & EventConditionResponseByDrawAllOf,
      'seconds' | 'shape'
    >
  >;
