/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventEntryStatsResponseData} from './eventEntryStatsResponseData';
import type {EventEntryStatsExcelResponseResultCode} from './eventEntryStatsExcelResponseResultCode';

/**
 * 이벤트 응모 통계 엑셀 Response
 */
export interface EventEntryStatsExcelResponse {
  data: EventEntryStatsResponseData[];
  resultCode?: EventEntryStatsExcelResponseResultCode;
  resultMessage?: string;
}
