/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventAdminResponseData} from './eventAdminResponseData';
import type {EventAdminDetailResponseResultCode} from './eventAdminDetailResponseResultCode';

/**
 * 이벤트 상세 조회 Response
 */
export interface EventAdminDetailResponse {
  data: EventAdminResponseData;
  resultCode?: EventAdminDetailResponseResultCode;
  resultMessage?: string;
}
