/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventEntryDataVO} from './eventEntryDataVO';
import type {FindEventEntryDataAllOf} from './findEventEntryDataAllOf';

export type FindEventEntryData = EventEntryDataVO &
  FindEventEntryDataAllOf &
  Required<Pick<EventEntryDataVO & FindEventEntryDataAllOf, 'seconds'>>;
