/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {GetAdPlacementByAppIdListProviderType} from './getAdPlacementByAppIdListProviderType';
import type {GetAdPlacementByAppIdListAdOrderType} from './getAdPlacementByAppIdListAdOrderType';

export type GetAdPlacementByAppIdListParams = {
  name?: string;
  providerType?: GetAdPlacementByAppIdListProviderType;
  adOrderType?: GetAdPlacementByAppIdListAdOrderType;
  page?: number;
  size?: number;
  fromDate?: string;
  toDate?: string;
};
