/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {GetEventByAppIdListRewardStatus} from './getEventByAppIdListRewardStatus';

export type GetEventByAppIdListParams = {
  adid?: string;
  idfa?: string;
  platform?: string;
  clickKey?: string;
  userId?: string;
  win?: boolean;
  rewardStatus?: GetEventByAppIdListRewardStatus;
  page?: number;
  size?: number;
  fromDate?: string;
  toDate?: string;
};
