/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {GetReportStatsProviderType} from './getReportStatsProviderType';

export type GetReportStatsParams = {
  providerType?: GetReportStatsProviderType;
  placementName?: string;
  page?: number;
  size?: number;
  fromDate?: string;
  toDate?: string;
};
