/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {ReportStatsResponseData} from './reportStatsResponseData';
import type {SortObject} from './sortObject';
import type {PageableObject} from './pageableObject';

export interface PageReportStatsResponseData {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: ReportStatsResponseData[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  pageable?: PageableObject;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
}
