/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

export interface PasswordResetRequest {
  /**
   * 초기화 비밀번호
   * @minLength 4
   * @maxLength 2147483647
   */
  temporaryPassword: string;
}
