/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {ReportProviderResponseDataProviderType} from './reportProviderResponseDataProviderType';
import type {ReportProviderResponseDataReportProviderType} from './reportProviderResponseDataReportProviderType';

/**
 * 리포트 매체 Response Data
 */
export interface ReportProviderResponseData {
  id: string;
  appId: string;
  providerType: ReportProviderResponseDataProviderType;
  reportProviderType: ReportProviderResponseDataReportProviderType;
  commission: number;
  reportKey: string;
}
