/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {ReportProviderCreateRequestProviderType} from './reportProviderCreateRequestProviderType';
import type {ReportProviderCreateRequestReportProviderType} from './reportProviderCreateRequestReportProviderType';

/**
 * 리포트 매체 생성 요청 Request
 */
export interface ReportProviderCreateRequest {
  /** 매체 */
  providerType: ReportProviderCreateRequestProviderType;
  /** 리포트 매체 */
  reportProviderType: ReportProviderCreateRequestReportProviderType;
  /** 리포트 API Key */
  reportKey: string;
  /** 수수료율 */
  commission: number;
}
