/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 매체
 */
export type ReportProviderCreateRequestProviderType =
  (typeof ReportProviderCreateRequestProviderType)[keyof typeof ReportProviderCreateRequestProviderType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportProviderCreateRequestProviderType = {
  MEZZO: 'MEZZO',
  ADPOPCORN: 'ADPOPCORN',
  DAWIN: 'DAWIN',
  GOOGLE: 'GOOGLE',
} as const;
