/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 리포트 매체 수정 요청 Request
 */
export interface ReportProviderUpdateRequest {
  /** 리포트 API Key */
  reportKey: string;
  /** 수수료율 */
  commission: number;
}
