/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {ReportStatsResponseDataProviderType} from './reportStatsResponseDataProviderType';

export interface ReportStatsResponseData {
  appId: string;
  providerType: ReportStatsResponseDataProviderType;
  dateKey: string;
  placementId: string;
  placementName: string;
  request: number;
  impression: number;
  click: number;
  revenue: number;
  ecpm: number;
}
