/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 리포트 매체
 */
export type ReportProviderCreateRequestReportProviderType =
  (typeof ReportProviderCreateRequestReportProviderType)[keyof typeof ReportProviderCreateRequestReportProviderType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportProviderCreateRequestReportProviderType = {
  MEZZO: 'MEZZO',
  MEZZO_VIDEO: 'MEZZO_VIDEO',
  ADPOPCORN: 'ADPOPCORN',
  GOOGLE: 'GOOGLE',
  DAWIN: 'DAWIN',
} as const;
