/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

export type ReportProviderResponseDataReportProviderType =
  (typeof ReportProviderResponseDataReportProviderType)[keyof typeof ReportProviderResponseDataReportProviderType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportProviderResponseDataReportProviderType = {
  MEZZO: 'MEZZO',
  MEZZO_VIDEO: 'MEZZO_VIDEO',
  ADPOPCORN: 'ADPOPCORN',
  GOOGLE: 'GOOGLE',
  DAWIN: 'DAWIN',
} as const;
