/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

export type SaveReportStatsParams = {
  /**
   * 배치 실행시작일자
   */
  fromDate: string;
  /**
   * 배치 실행종료일자
   */
  toDate: string;
};
