/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {PageUserModel} from './pageUserModel';
import type {UserInfoPageResponseResultCode} from './userInfoPageResponseResultCode';

/**
 * 사용자 정보 페이지목록 Response
 */
export interface UserInfoPageResponse {
  data: PageUserModel;
  resultCode?: UserInfoPageResponseResultCode;
  resultMessage?: string;
}
