/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 내 정보 수정
 */
export interface UserMyInfoUpdateRequest {
  /**
   * 현재 비밀번호
   * @minLength 4
   * @maxLength 2147483647
   */
  oldPassword: string;
  /**
   * 변경할 비밀번호
   * @minLength 4
   * @maxLength 2147483647
   */
  password: string;
  /**
   * 이름
   * @minLength 1
   */
  fullName: string;
  /** 이메일 */
  email: string;
  /** 전화번호 */
  phone?: string;
}
