/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {UserRoleUpdateRequestRole} from './userRoleUpdateRequestRole';

/**
 * 사용자 정보 수정 - Role 변경
 */
export interface UserRoleUpdateRequest {
  /** 사용자 역할 (ADMIN 또는 MANAGER만 가능) */
  role: UserRoleUpdateRequestRole;
}
