/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {UserRoleModel} from './userRoleModel';

export interface UserModel {
  id: string;
  username: string;
  email: string;
  fullName: string;
  enabled: boolean;
  appId?: string;
  roles: UserRoleModel[];
  phone?: string;
}
