/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {UserModel} from './userModel';
import type {UserInfoResponseResultCode} from './userInfoResponseResultCode';

/**
 * 사용자 정보 Response
 */
export interface UserInfoResponse {
  data: UserModel;
  resultCode?: UserInfoResponseResultCode;
  resultMessage?: string;
}
