/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {AdPlacementByGoogleRequestAdOrderType} from './adPlacementByGoogleRequestAdOrderType';
import type {GoogleAdConfig} from './googleAdConfig';

/**
 * 구글 광고 지면 등록/수정 요청 Request
 */
export interface AdPlacementByGoogleRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  adOrderType: AdPlacementByGoogleRequestAdOrderType;
  /** 설정값 - android */
  android: GoogleAdConfig;
  /** 설정값 - ios */
  ios: GoogleAdConfig;
}
