/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {AdPlacementResponseDataProviderType} from './adPlacementResponseDataProviderType';
import type {AdPlacementResponseDataAdOrderType} from './adPlacementResponseDataAdOrderType';
import type {AdPlacementResponseDataAndroid} from './adPlacementResponseDataAndroid';
import type {AdPlacementResponseDataIos} from './adPlacementResponseDataIos';

/**
 * 광고 지면 Response Data
 */
export interface AdPlacementResponseData {
  id: string;
  appId: string;
  name?: string;
  description?: string;
  providerType: AdPlacementResponseDataProviderType;
  adOrderType: AdPlacementResponseDataAdOrderType;
  android?: AdPlacementResponseDataAndroid;
  ios?: AdPlacementResponseDataIos;
  createdAt?: string;
  updatedAt?: string;
}
