/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {AdPlacementByDawinRequestAdOrderType} from './adPlacementByDawinRequestAdOrderType';
import type {DawinAdConfig} from './dawinAdConfig';

/**
 * 다윈 광고 지면 등록/수정 요청 Request
 */
export interface AdPlacementByDawinRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  adOrderType: AdPlacementByDawinRequestAdOrderType;
  /** 설정값 - android */
  android: DawinAdConfig;
  /** 설정값 - ios */
  ios: DawinAdConfig;
}
