/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {PageAppResponseData} from './pageAppResponseData';
import type {AppListResponseResultCode} from './appListResponseResultCode';

/**
 * 앱 목록 Response
 */
export interface AppListResponse {
  data?: PageAppResponseData;
  resultCode?: AppListResponseResultCode;
  resultMessage?: string;
}
