/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {AppResponseData} from './appResponseData';
import type {AppResponseResultCode} from './appResponseResultCode';

/**
 * 앱 정보 Response
 */
export interface AppResponse {
  data: AppResponseData;
  resultCode?: AppResponseResultCode;
  resultMessage?: string;
}
