/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {CatchEventCreateRequestEventType} from './catchEventCreateRequestEventType';
import type {EventAdPlacementInfo} from './eventAdPlacementInfo';
import type {EventConditionByCatch} from './eventConditionByCatch';

/**
 * 잡기이벤트 생성 요청 DTO
 */
export interface CatchEventCreateRequest {
  /** 이벤트 유형 아이디 */
  eventType: CatchEventCreateRequestEventType;
  /**
   * 이벤트 이름
   * @minLength 1
   */
  displayName: string;
  /**
   * 설명
   * @minLength 1
   */
  summary: string;
  /**
   * 간략한 설명
   * @minLength 1
   */
  condition: string;
  /** 이벤트 리워드 가격 */
  rewardPrice: number;
  /** 이벤트 피드 URL */
  feedUrl?: string;
  /** 이벤트 아이콘 URL */
  iconUrl?: string;
  /** 이벤트 설명 */
  description?: string;
  /** 게시 여부 */
  isView: boolean;
  /** 인트로: 광고 지면 정보 */
  introAdPlacementInfo: EventAdPlacementInfo;
  /** 결과: 광고 지면 정보 */
  resultAdPlacementInfo: EventAdPlacementInfo;
  /** 이벤트 조건 */
  eventCondition: EventConditionByCatch;
  /**
   * 랜딩URL Path(도메인 하위 path)<br/>https://도메인/{path}
   * @minLength 1
   */
  landingPath: string;
  /**
   * 관리자 메뉴에 노출시킬 이벤트 메뉴명을 입력해 주세요.
   * @minLength 1
   */
  adminMenuName: string;
}
