/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * CS 답변
 */
export interface CSAnswerRequest {
  /**
   * 답변
   * @minLength 1
   */
  answer: string;
  /**
   * 답변자 이름
   * @minLength 1
   */
  answerName: string;
}
