/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {PageCSViewResponseData} from './pageCSViewResponseData';
import type {CSListResponseResultCode} from './cSListResponseResultCode';

/**
 * CS 정보 List Response
 */
export interface CSListResponse {
  data: PageCSViewResponseData;
  resultCode?: CSListResponseResultCode;
  resultMessage?: string;
}
