/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {CSStatusRequestStatus} from './cSStatusRequestStatus';

/**
 * CS 상태 및 메모 (IN_PROGRESS, ANSWERED)
 */
export interface CSStatusRequest {
  /**
   * 답변 상태
   * @minLength 1
   */
  status: CSStatusRequestStatus;
  /**
   * 답변
   * @minLength 1
   */
  memo: string;
}
