/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {CSViewResponseDataStatus} from './cSViewResponseDataStatus';
import type {CSViewResponseDataInquireType} from './cSViewResponseDataInquireType';

/**
 * CS 정보 Response Data
 */
export interface CSViewResponseData {
  /** CS ID */
  id?: string;
  /** 앱 ID */
  appId: string;
  /** 클릭 키 */
  clickKey: string;
  /** 사용자 ID */
  userId: string;
  /** 플랫폼 */
  platform: string;
  /** ADID */
  adid: string;
  /** IDFA */
  idfa: string;
  /** 질문 */
  question: string;
  /** 답변 */
  answer: string;
  /** 답변자 이름 */
  answerName: string;
  /** 메모 */
  memo: string;
  /** 이메일 */
  email: string;
  /** 이메일 발송 여부 */
  sendEmail: boolean;
  /** 처리 상태 */
  status: CSViewResponseDataStatus;
  /** 문의 유형 */
  inquireType: CSViewResponseDataInquireType;
  /** 이벤트 ID */
  eventId: string;
  /** 파일 목록 */
  files: string[];
  /** 생성 일자 */
  createDateAt: string;
  /** 생성 시간 */
  createdAt?: string;
  /** 수정 시간 */
  updatedAt?: string;
}
