/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 문의 유형
 */
export type CSViewResponseDataInquireType =
  (typeof CSViewResponseDataInquireType)[keyof typeof CSViewResponseDataInquireType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CSViewResponseDataInquireType = {
  POINT_INQUIRY: 'POINT_INQUIRY',
  AD_PARTICIPATION: 'AD_PARTICIPATION',
  SERVICE_ISSUE: 'SERVICE_ISSUE',
  OTHER: 'OTHER',
} as const;
