/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventEntryStatsResponseDataEventType} from './eventEntryStatsResponseDataEventType';

/**
 * 이벤트 응모 통계 Response Data
 */
export interface EventEntryStatsResponseData {
  appId: string;
  dateKey: string;
  eventType: EventEntryStatsResponseDataEventType;
  eventId: string;
  totalEntryCount: number;
  uniqueUserCount: number;
  rewardCompletedCount: number;
}
