/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventEntryResponseDataData} from './eventEntryResponseDataData';
import type {EventEntryResponseDataRewardStatus} from './eventEntryResponseDataRewardStatus';

/**
 * 이벤트 응모 이력 Response Data
 */
export interface EventEntryResponseData {
  id?: string;
  appId: string;
  adid?: string;
  idfa?: string;
  platform?: string;
  clickKey: string;
  userId: string;
  data?: EventEntryResponseDataData;
  win: boolean;
  dateKey: string;
  createdAt?: string;
  rewardStatus: EventEntryResponseDataRewardStatus;
  rewardedAt?: string;
  rewardPostbackUrl?: string;
  rewardResponseBody?: string;
}
