/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventConditionResponseByCatch} from './eventConditionResponseByCatch';
import type {EventConditionResponseByDraw} from './eventConditionResponseByDraw';
import type {EventConditionResponseByFind} from './eventConditionResponseByFind';
import type {EventConditionResponseByRoulette} from './eventConditionResponseByRoulette';

export type EventAdminResponseDataEventCondition =
  | EventConditionResponseByCatch
  | EventConditionResponseByDraw
  | EventConditionResponseByFind
  | EventConditionResponseByRoulette;
