/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {CatchEventEntryData} from './catchEventEntryData';
import type {DrawEventEntryData} from './drawEventEntryData';
import type {FindEventEntryData} from './findEventEntryData';
import type {RouletteEventEntryData} from './rouletteEventEntryData';

export type EventEntryResponseDataData =
  | CatchEventEntryData
  | DrawEventEntryData
  | FindEventEntryData
  | RouletteEventEntryData;
