/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {PageEventAdminResponseData} from './pageEventAdminResponseData';
import type {EventAdminListResponseResultCode} from './eventAdminListResponseResultCode';

/**
 * 이벤트 목록 Response
 */
export interface EventAdminListResponse {
  data: PageEventAdminResponseData;
  resultCode?: EventAdminListResponseResultCode;
  resultMessage?: string;
}
