/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {ImageUploadResponseResultCode} from './imageUploadResponseResultCode';

/**
 * 이미지 업로드 Response
 */
export interface ImageUploadResponse {
  /** 업로드된 이미지 URL */
  url: string;
  resultCode?: ImageUploadResponseResultCode;
  resultMessage?: string;
}
