/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {UserRoleModel} from './userRoleModel';

export interface LoginResponseData {
  token: string;
  userId: string;
  username: string;
  email: string;
  fullName: string;
  appId?: string;
  roles: UserRoleModel[];
  isTemporaryPassword: boolean;
}
