/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {LoginResponseData} from './loginResponseData';
import type {LoginResponseResultCode} from './loginResponseResultCode';

/**
 * 로그인 Response
 */
export interface LoginResponse {
  data: LoginResponseData;
  resultCode?: LoginResponseResultCode;
  resultMessage?: string;
}
