/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {UserModel} from './userModel';
import type {SortObject} from './sortObject';
import type {PageableObject} from './pageableObject';

export interface PageUserModel {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: UserModel[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  pageable?: PageableObject;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
}
