/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {ReportProviderResponseData} from './reportProviderResponseData';
import type {ReportProviderResponseResultCode} from './reportProviderResponseResultCode';

/**
 * 리포트 매체 상세 조회 Response
 */
export interface ReportProviderResponse {
  data: ReportProviderResponseData;
  resultCode?: ReportProviderResponseResultCode;
  resultMessage?: string;
}
