/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {ReportProviderResponseData} from './reportProviderResponseData';
import type {ReportProviderListResponseResultCode} from './reportProviderListResponseResultCode';

/**
 * 리포트 매체 목록 Response
 */
export interface ReportProviderListResponse {
  data: ReportProviderResponseData[];
  resultCode?: ReportProviderListResponseResultCode;
  resultMessage?: string;
}
