/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import type {ReportStatsResponseData} from './reportStatsResponseData';
import type {ReportStatsExcelResponseResultCode} from './reportStatsExcelResponseResultCode';

export interface ReportStatsExcelResponse {
  data: ReportStatsResponseData[];
  resultCode?: ReportStatsExcelResponseResultCode;
  resultMessage?: string;
}
