/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 이벤트 유형 아이디
 */
export type RouletteEventUpdateRequestEventType =
  (typeof RouletteEventUpdateRequestEventType)[keyof typeof RouletteEventUpdateRequestEventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RouletteEventUpdateRequestEventType = {
  CATCH: 'CATCH',
  DRAW: 'DRAW',
  FIND: 'FIND',
  ROULETTE: 'ROULETTE',
  UNKNOWN: 'UNKNOWN',
} as const;
