/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 사용자 역할 (ADMIN 또는 MANAGER만 가능)
 */
export type UserUpdateRequestRole =
  (typeof UserUpdateRequestRole)[keyof typeof UserUpdateRequestRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserUpdateRequestRole = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
} as const;
