/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 사용자 상태 수정
 */
export interface UserStatusUpdateRequest {
  /** 사용자 활성화 상태 */
  enabled: boolean;
}
