/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 사용자 정보 수정
 */
export interface UserInfoUpdateRequest {
  /**
   * 이름
   * @minLength 1
   */
  fullName: string;
  /** 이메일 */
  email: string;
  /** 전화번호 */
  phone?: string;
}
