/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */

export type UserRoleModelRole =
  (typeof UserRoleModelRole)[keyof typeof UserRoleModelRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRoleModelRole = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;
