/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: Admin API
 * 핀플로우 프로모션: Admin API 문서
 * OpenAPI spec version: 1.0
 */
import {useMutation, useQuery, useSuspenseQuery} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type {
  AppByUserResponse,
  AppListResponse,
  AppRequest,
  AppResponse,
  AppUpdateRequest,
  EmptyResponse,
  GetAppListParams,
} from '.././model';

import {customFetch} from '../../custom-fetch.client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 앱 ID를 기반으로 앱의 상세 정보를 조회합니다.
 * @summary 앱 상세 조회
 */
export const getGetAppDetailUrl = (appId: string) => {
  return `/admin/api/apps/${appId}`;
};

export const getAppDetail = async (
  appId: string,
  options?: RequestInit,
): Promise<AppResponse> => {
  return customFetch<AppResponse>(getGetAppDetailUrl(appId), {
    ...options,
    method: 'GET',
  });
};

export const getGetAppDetailQueryKey = (appId: string) => {
  return [`/admin/api/apps/${appId}`] as const;
};

export const getGetAppDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getAppDetail>>,
  TError = unknown,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAppDetail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAppDetailQueryKey(appId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAppDetail>>> = ({
    signal,
  }) => getAppDetail(appId, {signal, ...requestOptions});

  return {
    queryKey,
    queryFn,
    enabled: !!appId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAppDetail>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetAppDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAppDetail>>
>;
export type GetAppDetailQueryError = unknown;

export function useGetAppDetail<
  TData = Awaited<ReturnType<typeof getAppDetail>>,
  TError = unknown,
>(
  appId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAppDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAppDetail>>,
          TError,
          Awaited<ReturnType<typeof getAppDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAppDetail<
  TData = Awaited<ReturnType<typeof getAppDetail>>,
  TError = unknown,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAppDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAppDetail>>,
          TError,
          Awaited<ReturnType<typeof getAppDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetAppDetail<
  TData = Awaited<ReturnType<typeof getAppDetail>>,
  TError = unknown,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAppDetail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary 앱 상세 조회
 */

export function useGetAppDetail<
  TData = Awaited<ReturnType<typeof getAppDetail>>,
  TError = unknown,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAppDetail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAppDetailQueryOptions(appId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>};

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAppDetailSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getAppDetail>>,
  TError = unknown,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAppDetailQueryKey(appId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAppDetail>>> = ({
    signal,
  }) => getAppDetail(appId, {signal, ...requestOptions});

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getAppDetail>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetAppDetailSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAppDetail>>
>;
export type GetAppDetailSuspenseQueryError = unknown;

export function useGetAppDetailSuspense<
  TData = Awaited<ReturnType<typeof getAppDetail>>,
  TError = unknown,
>(
  appId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAppDetailSuspense<
  TData = Awaited<ReturnType<typeof getAppDetail>>,
  TError = unknown,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAppDetailSuspense<
  TData = Awaited<ReturnType<typeof getAppDetail>>,
  TError = unknown,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 앱 상세 조회
 */

export function useGetAppDetailSuspense<
  TData = Awaited<ReturnType<typeof getAppDetail>>,
  TError = unknown,
>(
  appId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAppDetailSuspenseQueryOptions(appId, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 앱 정보 수정
 */
export const getUpdateAppUrl = (appId: string) => {
  return `/admin/api/apps/${appId}`;
};

export const updateApp = async (
  appId: string,
  appUpdateRequest: AppUpdateRequest,
  options?: RequestInit,
): Promise<EmptyResponse> => {
  return customFetch<EmptyResponse>(getUpdateAppUrl(appId), {
    ...options,
    method: 'PUT',
    headers: {'Content-Type': 'application/json', ...options?.headers},
    body: JSON.stringify(appUpdateRequest),
  });
};

export const getUpdateAppMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateApp>>,
    TError,
    {appId: string; data: AppUpdateRequest},
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateApp>>,
  TError,
  {appId: string; data: AppUpdateRequest},
  TContext
> => {
  const mutationKey = ['updateApp'];
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateApp>>,
    {appId: string; data: AppUpdateRequest}
  > = (props) => {
    const {appId, data} = props ?? {};

    return updateApp(appId, data, requestOptions);
  };

  return {mutationFn, ...mutationOptions};
};

export type UpdateAppMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateApp>>
>;
export type UpdateAppMutationBody = AppUpdateRequest;
export type UpdateAppMutationError = unknown;

/**
 * @summary 앱 정보 수정
 */
export const useUpdateApp = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateApp>>,
      TError,
      {appId: string; data: AppUpdateRequest},
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateApp>>,
  TError,
  {appId: string; data: AppUpdateRequest},
  TContext
> => {
  const mutationOptions = getUpdateAppMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 새로운 앱을 등록합니다.
 * @summary 앱 신규 등록
 */
export const getCreateAppUrl = () => {
  return `/admin/api/apps`;
};

export const createApp = async (
  appRequest: AppRequest,
  options?: RequestInit,
): Promise<EmptyResponse> => {
  return customFetch<EmptyResponse>(getCreateAppUrl(), {
    ...options,
    method: 'POST',
    headers: {'Content-Type': 'application/json', ...options?.headers},
    body: JSON.stringify(appRequest),
  });
};

export const getCreateAppMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createApp>>,
    TError,
    {data: AppRequest},
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createApp>>,
  TError,
  {data: AppRequest},
  TContext
> => {
  const mutationKey = ['createApp'];
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createApp>>,
    {data: AppRequest}
  > = (props) => {
    const {data} = props ?? {};

    return createApp(data, requestOptions);
  };

  return {mutationFn, ...mutationOptions};
};

export type CreateAppMutationResult = NonNullable<
  Awaited<ReturnType<typeof createApp>>
>;
export type CreateAppMutationBody = AppRequest;
export type CreateAppMutationError = unknown;

/**
 * @summary 앱 신규 등록
 */
export const useCreateApp = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createApp>>,
      TError,
      {data: AppRequest},
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createApp>>,
  TError,
  {data: AppRequest},
  TContext
> => {
  const mutationOptions = getCreateAppMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 필터와 페이징 정보를 기반으로 앱 목록을 조회합니다.<br/><br/>- 필터 조건은 JSON 형식으로 전달됩니다.<br/><br/>- 예시) {"name":"애드포러스"}
 * @summary 앱 목록 조회
 */
export const getGetAppListUrl = (params?: GetAppListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/admin/api/apps/list?${stringifiedParams}`
    : `/admin/api/apps/list`;
};

export const getAppList = async (
  params?: GetAppListParams,
  options?: RequestInit,
): Promise<AppListResponse> => {
  return customFetch<AppListResponse>(getGetAppListUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetAppListQueryKey = (params?: GetAppListParams) => {
  return [`/admin/api/apps/list`, ...(params ? [params] : [])] as const;
};

export const getGetAppListQueryOptions = <
  TData = Awaited<ReturnType<typeof getAppList>>,
  TError = unknown,
>(
  params?: GetAppListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAppList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAppListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAppList>>> = ({
    signal,
  }) => getAppList(params, {signal, ...requestOptions});

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getAppList>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetAppListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAppList>>
>;
export type GetAppListQueryError = unknown;

export function useGetAppList<
  TData = Awaited<ReturnType<typeof getAppList>>,
  TError = unknown,
>(
  params: undefined | GetAppListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAppList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAppList>>,
          TError,
          Awaited<ReturnType<typeof getAppList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAppList<
  TData = Awaited<ReturnType<typeof getAppList>>,
  TError = unknown,
>(
  params?: GetAppListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAppList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAppList>>,
          TError,
          Awaited<ReturnType<typeof getAppList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetAppList<
  TData = Awaited<ReturnType<typeof getAppList>>,
  TError = unknown,
>(
  params?: GetAppListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAppList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary 앱 목록 조회
 */

export function useGetAppList<
  TData = Awaited<ReturnType<typeof getAppList>>,
  TError = unknown,
>(
  params?: GetAppListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAppList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAppListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>};

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAppListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getAppList>>,
  TError = unknown,
>(
  params?: GetAppListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAppListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAppList>>> = ({
    signal,
  }) => getAppList(params, {signal, ...requestOptions});

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getAppList>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetAppListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAppList>>
>;
export type GetAppListSuspenseQueryError = unknown;

export function useGetAppListSuspense<
  TData = Awaited<ReturnType<typeof getAppList>>,
  TError = unknown,
>(
  params: undefined | GetAppListParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAppListSuspense<
  TData = Awaited<ReturnType<typeof getAppList>>,
  TError = unknown,
>(
  params?: GetAppListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAppListSuspense<
  TData = Awaited<ReturnType<typeof getAppList>>,
  TError = unknown,
>(
  params?: GetAppListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 앱 목록 조회
 */

export function useGetAppListSuspense<
  TData = Awaited<ReturnType<typeof getAppList>>,
  TError = unknown,
>(
  params?: GetAppListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAppListSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 로그인 유저에 따른 앱 목록 조회: 우측 상단 dropdown 목록 노출용
 */
export const getGetAppListByUserUrl = () => {
  return `/admin/api/apps/list-by-user`;
};

export const getAppListByUser = async (
  options?: RequestInit,
): Promise<AppByUserResponse> => {
  return customFetch<AppByUserResponse>(getGetAppListByUserUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetAppListByUserQueryKey = () => {
  return [`/admin/api/apps/list-by-user`] as const;
};

export const getGetAppListByUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getAppListByUser>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAppListByUser>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAppListByUserQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAppListByUser>>
  > = ({signal}) => getAppListByUser({signal, ...requestOptions});

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getAppListByUser>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetAppListByUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAppListByUser>>
>;
export type GetAppListByUserQueryError = unknown;

export function useGetAppListByUser<
  TData = Awaited<ReturnType<typeof getAppListByUser>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAppListByUser>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAppListByUser>>,
          TError,
          Awaited<ReturnType<typeof getAppListByUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAppListByUser<
  TData = Awaited<ReturnType<typeof getAppListByUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAppListByUser>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAppListByUser>>,
          TError,
          Awaited<ReturnType<typeof getAppListByUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetAppListByUser<
  TData = Awaited<ReturnType<typeof getAppListByUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAppListByUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary 로그인 유저에 따른 앱 목록 조회: 우측 상단 dropdown 목록 노출용
 */

export function useGetAppListByUser<
  TData = Awaited<ReturnType<typeof getAppListByUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAppListByUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAppListByUserQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>};

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAppListByUserSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getAppListByUser>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getAppListByUser>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAppListByUserQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAppListByUser>>
  > = ({signal}) => getAppListByUser({signal, ...requestOptions});

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getAppListByUser>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetAppListByUserSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAppListByUser>>
>;
export type GetAppListByUserSuspenseQueryError = unknown;

export function useGetAppListByUserSuspense<
  TData = Awaited<ReturnType<typeof getAppListByUser>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppListByUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAppListByUserSuspense<
  TData = Awaited<ReturnType<typeof getAppListByUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppListByUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAppListByUserSuspense<
  TData = Awaited<ReturnType<typeof getAppListByUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppListByUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 로그인 유저에 따른 앱 목록 조회: 우측 상단 dropdown 목록 노출용
 */

export function useGetAppListByUserSuspense<
  TData = Awaited<ReturnType<typeof getAppListByUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAppListByUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAppListByUserSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
